### ISSUE TITLE
[FE][FEAT] BTS 앱 만들기

### ISSUE THREAD

**Issue by SeyeonJang** [SeyeonJang/AndroidStudy#2]
## ✅ Feature :: BTS 앱 만들기
- 주제 : Section1. BTS 앱 만들기
- 주요 기술 : ImageView, Layout, findViewById, Toast, Intent 전환, Activity 전환
</br>

## 😎 Preview
- 학습한 강의 커리큘럼 스크린샷
<img width="979" alt="image" src="https://github.com/SeyeonJang/AndroidStudy/assets/47477205/488b0d09-15b0-4d06-a028-601a3b8174d8">

- 앱 스크린샷
<br/>

## ✏️ To-do
- [ ] 이미지뷰(ImageView), Drawable 폴더
- [ ] Linear Layout, Relative Layout, Constraint Layout
- [ ] 레이아웃에 사진 삽입
- [ ] 화면 클릭 이벤트 처리 - findViewById, Toast
- [ ] 화면(액티비티) 새로 만들기, 화면전환(Intent)
- [ ] 여러개의 액티비티(Activity) 화면전환

</br>
